version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: joy_of_painting_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: joy_user
      POSTGRES_PASSWORD: joy_painting_2024
      POSTGRES_DB: joy_of_painting
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    networks:
      - joy_network

  # pgAdmin - Database Administration Tool (Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: joy_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@joyofpainting.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - joy_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  joy_network:
    driver: bridge
